# .github/workflows/deploy-to-ec2.yml
name: Deploy to EC2 on Push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/msa-deploy
            docker-compose pull
            docker-compose down
            docker-compose up -d
