name: Build and Push MSA Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [
          flight-service,
          flight-reservation-server,
          user-service,
          flight-reservation-gateway,
          reservation-service,
          flight-reservation-front-main  # ✅ 프론트 추가
        ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17 (only for backend)
        if: ${{ matrix.service != 'flight-reservation-front-main' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permission for Gradle wrapper (only for backend)
        if: ${{ matrix.service != 'flight-reservation-front-main' }}
        run: chmod +x ${{ matrix.service }}/gradlew

      - name: Build JAR for ${{ matrix.service }} (only for backend)
        if: ${{ matrix.service != 'flight-reservation-front-main' }}
        run: |
          cd ${{ matrix.service }}
          ./gradlew clean bootJar -x test
          cd ..

      - name: Install Node.js (only for frontend)
        if: ${{ matrix.service == 'flight-reservation-front-main' }}
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build React frontend (only for frontend)
        if: ${{ matrix.service == 'flight-reservation-front-main' }}
        run: |
          cd ${{ matrix.service }}
          npm install
          npm run build
          cd ..

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image for ${{ matrix.service }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

#  deploy-to-ec2:
#    needs: build-and-push
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to EC2 via SSH
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_KEY }}
#          script: |
#            cd ~/msa-deploy
#            docker-compose pull
#            docker-compose down
#            docker-compose up -d
